/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/d1e12d1c-6b87-41be-a810-fa76899ac7a9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch led1;
  CloudSwitch led2;
  CloudSwitch led3;
  CloudSwitch led4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "arduino_secret.h"
const int s1 = 5; //D1
const int s2 = 4; //D2
const int s3 = 0; //D3
const int s4 = 2; //D4

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
pinMode(s1,OUTPUT);
pinMode(s2,OUTPUT);
pinMode(s3,OUTPUT);
pinMode(s4,OUTPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since Led1 is READ_WRITE variable, onLed1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed1Change()  {
  // Add your code here to act upon Led1 change

  if(led1)
  {
    digitalWrite(s1,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(s1,LOW);
    Serial.println("OFF");
  }
}

/*
  Since Led2 is READ_WRITE variable, onLed2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed2Change()  {
  // Add your code here to act upon Led2 change

  if(led2)
  {
    digitalWrite(s2,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(s2,LOW);
    Serial.println("OFF");
  }
}

/*
  Since Led3 is READ_WRITE variable, onLed3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed3Change()  {
  // Add your code here to act upon Led3 change

  if(led3)
  {
    digitalWrite(s3,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(s3,LOW);
    Serial.println("OFF");
  }
}

/*
  Since Led4 is READ_WRITE variable, onLed4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed4Change()  {
  // Add your code here to act upon Led4 change

  if(led4)
  {
    digitalWrite(s4,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(s4,LOW);
    Serial.println("OFF");
  }
}

