// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secret.h"

const char DEVICE_LOGIN_NAME[]  = "ee345528-d958-4147-927d-bca4372a21c1";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLed1Change();
void onLed2Change();
void onLed3Change();
void onLed4Change();

CloudSwitch led1;
CloudSwitch led2;
CloudSwitch led3;
CloudSwitch led4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led1, READWRITE, ON_CHANGE, onLed1Change);
  ArduinoCloud.addProperty(led2, READWRITE, ON_CHANGE, onLed2Change);
  ArduinoCloud.addProperty(led3, READWRITE, ON_CHANGE, onLed3Change);
  ArduinoCloud.addProperty(led4, READWRITE, ON_CHANGE, onLed4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
